name: Linters

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  reviewdog:
    name: 🧪 ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: yarn install

      - name: Run eslint with reviewdog
        uses: reviewdog/action-eslint@v1.33.0
        with:
          eslint_flags: . --ext .js,.jsx,.ts,.tsx
