name: Linters

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  reviewdog:
    name: 🧪 ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: yarn install

      - name: Run eslint with reviewdog
        uses: reviewdog/action-eslint@v1.16.1
